### ISSUE TITLE
Errors generated by scripts in 03_Telnet_from_Linked_File

### ISSUE THREAD

**Issue by Collisio-Adolebitque** [Collisio-Adolebitque/DB_PFNE#1]
Errors generated by scripts in [03_Telnet_from_Linked_File](https://github.com/Collisio-Adolebitque/DB_PFNE/tree/master/apps/03_Telnet_from_Linked_File) scripts:

`Configuring switch IOS-SW7 with IP address: .
Traceback (most recent call last):
  File "rollbackIOS-SW-from-file.py", line 55, in <module>
    main()
  File "rollbackIOS-SW-from-file.py", line 18, in main
    tn = telnetlib.Telnet(host)
  File "/usr/lib/python3.5/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known`

**Comment by Collisio-Adolebitque** [comment]
Issue caused by additional line in switches.txt.  Removed line; error stopped.
