### ISSUE TITLE
Netmiko connecting from GNS3 Network Automation container to 3725 image fails to configure VLANs

### ISSUE THREAD

**Issue by Collisio-Adolebitque** [Collisio-Adolebitque/DB_PFNE#4]
I don't have access to IOU / VIRL images, so I've been running the course against an old 3725 image that doesn't take vlan commands from config mode

```
# First pass at Netmiko from DBs Python Network Programming for Network Engineers (Python 3)
import getpass
from netmiko import ConnectHandler
 
 
def main():
    user = input("Enter your remote account: ")
    password = getpass.getpass()
 
    iosv_l2 = {
        'device_type': 'cisco_ios',
        'ip': '192.168.122.72',
        'username': user,
        'password': password,
    }
 
    net_connect = ConnectHandler(**iosv_l2)
    output = net_connect.send_command('show ip interface brief')
    print(output)
 
    config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.255']
    output = net_connect.send_config_set(config_commands)
    print(output)
 
    for vlan_id in range(2, 21):
        print("Creating VLAN " + str(vlan_id) + ".")
        output = net_connect.send_command('vlan database', 'vlan ' + str(vlan_id) + 'name PYTHON_VLAN_' + str(vlan_id))
        print(output)
 
 
if __name__ == '__main__':
    main()
```

It mostly works, however, it fails on the VLAN creation portion as follows:

```
root@NetAutomate-1:~/scripts/P3FNE_Lab1# python3 programIOS_SW_Netmiko.py
Enter your remote account: admin
Password:
Interface                  IP-Address      OK? Method Status                Protocol
FastEthernet0/0            unassigned      YES NVRAM  administratively down down
Serial0/0                  unassigned      YES NVRAM  administratively down down
FastEthernet0/1            unassigned      YES NVRAM  administratively down down
Serial0/1                  unassigned      YES NVRAM  administratively down down
Serial0/2                  unassigned      YES NVRAM  administratively down down
Serial0/3                  unassigned      YES NVRAM  administratively down down
Serial0/4                  unassigned      YES NVRAM  administratively down down
Serial0/5                  unassigned      YES NVRAM  administratively down down
Serial1/0                  unassigned      YES NVRAM  administratively down down
Serial1/1                  unassigned      YES NVRAM  administratively down down
Serial1/2                  unassigned      YES NVRAM  administratively down down
Serial1/3                  unassigned      YES NVRAM  administratively down down
FastEthernet2/0            unassigned      YES unset  up                    up
FastEthernet2/1            unassigned      YES unset  up                    up
FastEthernet2/2            unassigned      YES unset  up                    up
FastEthernet2/3            unassigned      YES unset  up                    up
FastEthernet2/4            unassigned      YES unset  up                    up
FastEthernet2/5            unassigned      YES unset  up                    up
FastEthernet2/6            unassigned      YES unset  up                    up
FastEthernet2/7            unassigned      YES unset  up                    down
FastEthernet2/8            unassigned      YES unset  up                    down
FastEthernet2/9            unassigned      YES unset  up                    down
FastEthernet2/10           unassigned      YES unset  up                    down
FastEthernet2/11           unassigned      YES unset  up                    down
FastEthernet2/12           unassigned      YES unset  up                    down
FastEthernet2/13           unassigned      YES unset  up                    down
FastEthernet2/14           unassigned      YES unset  up                    down
FastEthernet2/15           unassigned      YES unset  up                    down
Vlan1                      172.16.39.150   YES NVRAM  up                    up
config term
Enter configuration commands, one per line.  End with CNTL/Z.
IOS-SW1(config)#int loop 0
IOS-SW1(config-if)#ip address 1.1.1.1 255.255.255.255
IOS-SW1(config-if)#end
IOS-SW1#
Traceback (most recent call last):
  File "programIOS_SW_Netmiko.py", line 35, in <module>
    main()
  File "programIOS_SW_Netmiko.py", line 25, in main
    output = net_connect.send_command('vlan database')
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1051, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: IOS\-SW1\#
```

**Comment by Collisio-Adolebitque** [comment]
I think I've got it.  It doesn't like the vlan database  prompts, script updated accordingly

```
# Fourth and final pass at Netmiko from DBs Python Network Programming for Network Engineers (Python 3)
import getpass
from netmiko import ConnectHandler
 
 
def main():
    ip_address = input("Please enter the IP address of the switch you would like to configure: ")
    user = input("Please enter your user name: ")
    password = getpass.getpass()
 
    iosv_l2 = {
        'device_type': 'cisco_ios',
        'ip': ip_address,
        'username': user,
        'password': password,
    }
 
    net_connect = ConnectHandler(**iosv_l2)
    net_connect.send_command('terminal length 0')
 
    print()
    print('Pre-change snapshot: ')
    print()
    output = net_connect.send_command('show vlan-switch brief')
    print(output)
    print()
    output = net_connect.send_command('show ip interface brief | ex unas')
    print(output)
 
    print()
    print('--------------------------------')
    print()
    print('Commence change: ')
    print()
    config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.255']
    output = net_connect.send_config_set(config_commands)
    print(output)
 
    output = net_connect.send_command('vlan database', expect_string='#')
    print(output)
    for vlan_id in range(2, 33):
        print("Creating VLAN " + str(vlan_id) + ".")
        output = net_connect.send_command('vlan ' + str(vlan_id) + ' name PYTHON_VLAN_' + str(vlan_id),
                                          expect_string='#')
        print(output)
    output = net_connect.send_command('exit', expect_string='#')
    print(output)
 
    print()
    print('--------------------------------')
    print()
    print('Post-change snapshot: ')
    print()
    output = net_connect.send_command('show ip interface brief | ex unas')
    print(output)
    output = net_connect.send_command('show vlan-switch brief')
    print(output)
 
 
if __name__ == '__main__':
    main()
```

Also, performance was significantly improved by moving the `vlan database` and `exit` commands out of the for loops.

```
root@NetAutomate-1:~/scripts/P3FNE_Lab1# python3 programIOS_SW_Netmiko.py
Please enter the IP address of the switch you would like to configure: 192.168.122.72
Please enter your user name: admin
Password:
Pre-change snapshot:
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Fa2/0, Fa2/1, Fa2/2, Fa2/3, Fa2/4, Fa2/5, Fa2/6, Fa2/7, Fa2/8, Fa2/9, Fa2/10, Fa2/11, Fa2/12, Fa2/13, Fa2/14, Fa2/15
1002 fddi-default                     active
1003 token-ring-default               active
1004 fddinet-default                  active
1005 trnet-default                    active
1#
IOS-SW1#
IOS-SW1#
--------------------------------
Commence change:
config term
Enter configuration commands, one per line.  End with CNTL/Z.
IOS-SW1(config)#int loop 0
IOS-SW1(config-if)#ip address 1.1.1.1 255.255.255.255
IOS-SW1(config-if)#end
IOS-SW1#
Creating VLAN 2.
VLAN 2 added:
    Name: PYTHON_VLAN_2
Creating VLAN 3.
VLAN 3 added:
    Name: PYTHON_VLAN_3
Creating VLAN 4.
VLAN 4 added:
    Name: PYTHON_VLAN_4
Creating VLAN 5.
VLAN 5 added:
    Name: PYTHON_VLAN_5
Creating VLAN 6.
VLAN 6 added:
    Name: PYTHON_VLAN_6
Creating VLAN 7.
VLAN 7 added:
    Name: PYTHON_VLAN_7
Creating VLAN 8.
VLAN 8 added:
    Name: PYTHON_VLAN_8
Creating VLAN 9.
VLAN 9 added:
    Name: PYTHON_VLAN_9
Creating VLAN 10.
VLAN 10 added:
    Name: PYTHON_VLAN_10
Creating VLAN 11.
VLAN 11 added:
    Name: PYTHON_VLAN_11
Creating VLAN 12.
VLAN 12 added:
    Name: PYTHON_VLAN_12
Creating VLAN 13.
VLAN 13 added:
    Name: PYTHON_VLAN_13
Creating VLAN 14.
VLAN 14 added:
    Name: PYTHON_VLAN_14
Creating VLAN 15.
VLAN 15 added:
    Name: PYTHON_VLAN_15
Creating VLAN 16.
VLAN 16 added:
    Name: PYTHON_VLAN_16
Creating VLAN 17.
VLAN 17 added:
    Name: PYTHON_VLAN_17
Creating VLAN 18.
VLAN 18 added:
    Name: PYTHON_VLAN_18
Creating VLAN 19.
VLAN 19 added:
    Name: PYTHON_VLAN_19
Creating VLAN 20.
VLAN 20 added:
    Name: PYTHON_VLAN_20
Creating VLAN 21.
VLAN 21 added:
    Name: PYTHON_VLAN_21
Creating VLAN 22.
VLAN 22 added:
    Name: PYTHON_VLAN_22
Creating VLAN 23.
VLAN 23 added:
    Name: PYTHON_VLAN_23
Creating VLAN 24.
VLAN 24 added:
    Name: PYTHON_VLAN_24
Creating VLAN 25.
VLAN 25 added:
    Name: PYTHON_VLAN_25
Creating VLAN 26.
VLAN 26 added:
    Name: PYTHON_VLAN_26
Creating VLAN 27.
VLAN 27 added:
    Name: PYTHON_VLAN_27
Creating VLAN 28.
VLAN 28 added:
    Name: PYTHON_VLAN_28
Creating VLAN 29.
VLAN 29 added:
    Name: PYTHON_VLAN_29
Creating VLAN 30.
VLAN 30 added:
    Name: PYTHON_VLAN_30
Creating VLAN 31.
VLAN 31 added:
    Name: PYTHON_VLAN_31
Creating VLAN 32.
VLAN 32 added:
    Name: PYTHON_VLAN_32
APPLY completed.
Exiting....
 
--------------------------------
 
Post-change snapshot:
IOS-SW1#
 
       IP-Address      OK? Method Status                Protocol
Vlan1                      172.16.39.150   YES NVRAM  up                    up
Loopback0                  1.1.1.1         YES manual up                    up
 
          Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Fa2/0, Fa2/1, Fa2/2, Fa2/3, Fa2/4, Fa2/5, Fa2/6, Fa2/7, Fa2/8, Fa2/9, Fa2/10, Fa2/11, Fa2/12, Fa2/13, Fa2/14, Fa2/15
2    PYTHON_VLAN_2                    active
3    PYTHON_VLAN_3                    active
4    PYTHON_VLAN_4                    active
5    PYTHON_VLAN_5                    active
6    PYTHON_VLAN_6                    active
7    PYTHON_VLAN_7                    active
8    PYTHON_VLAN_8                    active
9    PYTHON_VLAN_9                    active
10   PYTHON_VLAN_10                   active
11   PYTHON_VLAN_11                   active
12   PYTHON_VLAN_12                   active
13   PYTHON_VLAN_13                   active
14   PYTHON_VLAN_14                   active
15   PYTHON_VLAN_15                   active
16   PYTHON_VLAN_16                   active
17   PYTHON_VLAN_17                   active
18   PYTHON_VLAN_18                   active
19   PYTHON_VLAN_19                   active
20   PYTHON_VLAN_20                   active
21   PYTHON_VLAN_21                   active
22   PYTHON_VLAN_22                   active
23   PYTHON_VLAN_23                   active
24   PYTHON_VLAN_24                   active
25   PYTHON_VLAN_25                   active
26   PYTHON_VLAN_26                   active
27   PYTHON_VLAN_27                   active
28   PYTHON_VLAN_28                   active
29   PYTHON_VLAN_29                   active
30   PYTHON_VLAN_30                   active
31   PYTHON_VLAN_31                   active
32   PYTHON_VLAN_32                   active
1002 fddi-default                     active
1003 token-ring-default               active
1004 fddinet-default                  active
1005 trnet-default                    active
IOS-SW1#
```
